name: berlinTest
favicon: null
layout_spectrum: 0.72556
typography_spectrum: 0.72325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8a7e68'
    - '#010000'
    - '#4a595c'
    - '#d5c7aa'
    - '#562c1e'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
