name: berlinTest
favicon: null
layout_spectrum: 0.72556
typography_spectrum: 0.48125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbb7b4'
    - '#dfd8d2'
    - '#9c9d9f'
    - '#5c6d7d'
    - '#415264'
  brandStrength: 0.25
  lightness: 0.2434697630815208
  saturation: 0.9968991510104388
  rhythmicContrast: 0.18781885923817754
purpose: []
